# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arasaka.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'arasaka.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rarasaka.proto\x12\x07\x61rasaka\"F\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x17\n\x0fscore_threshold\x18\x03 \x01(\x01\"\xb4\x01\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x11\n\tanswer_id\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x35\n\x08metadata\x18\x05 \x03(\x0b\x32#.arasaka.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x0eSearchResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.arasaka.SearchResult\x12\x13\n\x0btotal_found\x18\x02 \x01(\x05\x12\r\n\x05query\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"\xd9\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12\x15\n\rqdrant_status\x18\x04 \x01(\t\x12\x44\n\x0f\x63ollection_info\x18\x05 \x03(\x0b\x32+.arasaka.HealthResponse.CollectionInfoEntry\x1a\x35\n\x13\x43ollectionInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x92\x01\n\x0e\x41rasakaService\x12@\n\rSearchAnswers\x12\x16.arasaka.SearchRequest\x1a\x17.arasaka.SearchResponse\x12>\n\x0bHealthCheck\x12\x16.arasaka.HealthRequest\x1a\x17.arasaka.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arasaka_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHRESPONSE_COLLECTIONINFOENTRY']._loaded_options = None
  _globals['_HEALTHRESPONSE_COLLECTIONINFOENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=26
  _globals['_SEARCHREQUEST']._serialized_end=96
  _globals['_SEARCHRESULT']._serialized_start=99
  _globals['_SEARCHRESULT']._serialized_end=279
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=232
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=279
  _globals['_SEARCHRESPONSE']._serialized_start=281
  _globals['_SEARCHRESPONSE']._serialized_end=373
  _globals['_HEALTHREQUEST']._serialized_start=375
  _globals['_HEALTHREQUEST']._serialized_end=390
  _globals['_HEALTHRESPONSE']._serialized_start=393
  _globals['_HEALTHRESPONSE']._serialized_end=610
  _globals['_HEALTHRESPONSE_COLLECTIONINFOENTRY']._serialized_start=557
  _globals['_HEALTHRESPONSE_COLLECTIONINFOENTRY']._serialized_end=610
  _globals['_ARASAKASERVICE']._serialized_start=613
  _globals['_ARASAKASERVICE']._serialized_end=759
# @@protoc_insertion_point(module_scope)
